CREATE TABLE tasks (
  id                    BINARY(16)                          NOT NULL,
  household_id          BINARY(16)                          NOT NULL,
  title                 VARCHAR(120)                        NOT NULL,
  icon                  VARCHAR(16)                         NOT NULL,
  notes                 VARCHAR(1000)                       NULL,
  audience              ENUM('adults','children','everyone')NOT NULL,
  points                INT UNSIGNED                        NOT NULL,
  recurrence_preset     ENUM('hourly','daily','weekly','monthly','custom') NOT NULL,
  recurrence_unit       ENUM('hours','days','weeks','months')              NOT NULL,
  recurrence_interval   INT UNSIGNED                        NOT NULL,
  next_due_at           DATETIME(3)                         NOT NULL,
  created_by_user_id    BINARY(16)                          NOT NULL,
  row_version           BIGINT UNSIGNED                     NOT NULL DEFAULT 1,
  created_at            DATETIME(3)                         NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at            DATETIME(3)                         NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at            DATETIME(3)                         NULL,
  PRIMARY KEY (id),
  KEY idx_tasks_household_due (household_id, next_due_at),
  KEY idx_tasks_household_deleted (household_id, deleted_at),
  KEY idx_tasks_row_version (household_id, row_version),
  CONSTRAINT fk_tasks_household FOREIGN KEY (household_id)       REFERENCES households(id),
  CONSTRAINT fk_tasks_creator   FOREIGN KEY (created_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
